{
 "title": "Demo 🔥🔥🔥",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rolled Replicas per Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_build_info{pod=~\"app.*\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "% of ping successes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100* sum(irate(\n            http_requests_total{handler=\"/ping\",code!~\"5.*\"}[20s]\n          )) /\n          sum(irate(\n            http_requests_total{handler=\"/ping\"}[20s]\n          ))"
    }
   ]
  },
  {
   "title": "Ping App requests per second by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (irate(http_requests_total{handler=\"/ping\"}[1m]))"
    }
   ]
  },
  {
   "title": "Version requests per second by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by(code, pod) (rate(http_requests_total{handler=\"/ping\", pod=~\"app.*\"}[1m])) * on(pod) group_left(version) app_build_info) by(code, version)"
    }
   ]
  },
  {
   "title": "Ping Client Latency (TOFIX)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_bucket{target=\"ping\", le!~\".Inf|120.0|90.0|720.0|360.0|240.0|60.0\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}